name: Generate Chain Specs

on:
  workflow_dispatch:
    inputs:
      tag_version:
        description: 'Tag version for the release'
        required: true
        type: string
      tag_suffix:
        description: 'Tag suffix to use (none for all packages)'
        required: true
        type: choice
        options:
          - none
          - relay
          - parachains
        default: 'none'
      build_paseo:
        description: 'Build paseo relay runtime'
        required: true
        type: boolean
        default: false
      build_asset_hub_paseo:
        description: 'Build asset-hub-paseo runtime'
        required: true
        type: boolean
        default: false
      build_bridge_hub_paseo:
        description: 'Build bridge-hub-paseo runtime'
        required: true
        type: boolean
        default: false
      build_collectives_paseo:
        description: 'Build collectives-paseo runtime'
        required: true
        type: boolean
        default: false
      build_people_paseo:
        description: 'Build people-paseo runtime'
        required: true
        type: boolean
        default: false
      build_coretime_paseo:
        description: 'Build coretime-paseo runtime'
        required: true
        type: boolean
        default: false
  workflow_call:
    inputs:
      tag_version:
        description: 'Tag version for the release'
        required: true
        type: string
      packages:
        description: 'Tag suffix (none, relay, parachains)'
        required: true
        type: string
      build_paseo:
        description: 'Build paseo relay runtime'
        required: false
        type: boolean
        default: false
      build_asset_hub_paseo:
        description: 'Build asset-hub-paseo runtime'
        required: false
        type: boolean
        default: false
      build_bridge_hub_paseo:
        description: 'Build bridge-hub-paseo runtime'
        required: false
        type: boolean
        default: false
      build_collectives_paseo:
        description: 'Build collectives-paseo runtime'
        required: false
        type: boolean
        default: false
      build_people_paseo:
        description: 'Build people-paseo runtime'
        required: false
        type: boolean
        default: false
      build_coretime_paseo:
        description: 'Build coretime-paseo runtime'
        required: false
        type: boolean
        default: false

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate-chain-specs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y git protobuf-compiler

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.84.1
          target: wasm32-unknown-unknown
          components: rust-src
          override: true

      - name: Add rust-src
        run: rustup component add rust-src --toolchain 1.81.0-x86_64-unknown-linux-gnu

      - name: Build chain-spec-generator
        run: cargo build --package chain-spec-generator --features=fast-runtime --release

      - name: Generate chain specs
        run: |
          mkdir -p chain-specs/local
          
          # Initialize empty array for packages
          PACKAGES=()
          
          # Add relay packages if selected
          if [[ "${{ inputs.build_paseo }}" == "true" || "${{ inputs.packages }}" == "relay" ]]; then
            PACKAGES+=("paseo-local" "paseo-dev")
          fi
          
          # Add parachain packages if selected
          if [[ "${{ inputs.build_asset_hub_paseo }}" == "true" || "${{ inputs.packages }}" == "parachains" ]]; then
            PACKAGES+=("asset-hub-paseo-local")
          fi
          
          if [[ "${{ inputs.build_bridge_hub_paseo }}" == "true" || "${{ inputs.packages }}" == "parachains" ]]; then
            PACKAGES+=("bridge-hub-paseo-local")
          fi
          
          if [[ "${{ inputs.build_collectives_paseo }}" == "true" || "${{ inputs.packages }}" == "parachains" ]]; then
            PACKAGES+=("collectives-paseo-local")
          fi
          
          if [[ "${{ inputs.build_people_paseo }}" == "true" || "${{ inputs.packages }}" == "parachains" ]]; then
            PACKAGES+=("people-paseo-local")
          fi
          
          if [[ "${{ inputs.build_coretime_paseo }}" == "true" || "${{ inputs.packages }}" == "parachains" ]]; then
            PACKAGES+=("coretime-paseo-local")
          fi
          
          # Generate specs for each package
          for pkg in "${PACKAGES[@]}"; do
            ./target/release/chain-spec-generator "$pkg" --raw > "chain-specs/local/$pkg.json"
            echo "Generated chain-specs/local/$pkg.json"
          done

      - name: Setup Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.CI_PAT }}

      - name: Commit changes
        run: |
          git add chain-specs/local/*.json
          if git diff --staged --quiet; then
            echo "No changes detected in chain specs. Skipping commit."
          else
            COMMIT_MESSAGE="Update chain specs for version ${{ inputs.tag_version }}"
            git commit -m "$COMMIT_MESSAGE"
            git push
            echo "Changes committed and pushed successfully."
          fi
